services:
  db:
    container_name: db
    image: postgres:17.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=richmindful100
      - POSTGRES_DB=bit
    ports:
      - 5432:5432
    logging:
      options:
        max-file: "3"
        max-size: "250m"
    networks:
      - app-network

  adminer:
    container_name: adminer
    image: dockette/adminer:dg
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - app-network

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: no
    ports:
      - 5002:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=postgresql://admin:richmindful100@db:5432/bit
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"
    networks:
      - app-network

  crawling:
    container_name: crawling
    build: 
      context: ./crawling  # Dockerfile이 있는 경로
      dockerfile: Dockerfile
    restart: no #always
    environment:
      - TZ=Asia/Seoul
      - PYTHONPATH=/app
    depends_on:
      - playwright
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"
    networks:
      - app-network

  playwright:
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    container_name: playwright
    ports:
      - "3210:3000"
    user: pwuser
    working_dir: /home/pwuser
    command: /bin/sh -c "npx -y playwright@1.50.0 run-server --port 3000 --host 0.0.0.0"
    init: true
    networks:
      - app-network
    
  vector_rag:
    container_name: vector_rag
    build: 
      context: ./vector_rag  # Dockerfile이 있는 경로
      dockerfile: Dockerfile
    restart: no #always
    ports:
      - 5001:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"  # 이 부분 추가! 호스트 머신 접근용
    environment:
      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
      - LANGSMITH_API_KEY=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
      - LANGSMITH_PROJECT="vector_store"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"
    networks:
      - app-network

  trade_signal_monitoring:
    container_name: trade_signal_monitoring
    build: 
      context: ./trade_signal_monitoring  # Dockerfile이 있는 경로
      dockerfile: Dockerfile
    restart: no #always
    environment:
      - TZ=Asia/Seoul
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
