services:
  db:
    container_name: db
    image: postgres:17.3
    restart: always
    #volumes:
    #- db-data:/var/lib/postgresql/data  # 볼륨 마운트 추가
    env_file:
      - .env
    ports:
      - 5432:5432
    logging:
      options:
        max-file: "3"
        max-size: "250m"

  adminer:
    container_name: adminer
    image: dockette/adminer:dg
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db

  crawling:
    container_name: crawling
    build:
      context: ./crawling # Dockerfile이 있는 경로
      dockerfile: Dockerfile
    restart: no #always
    #volumes:
    #- ./crawling:/app
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"

  backend:
    container_name: backend
    build:
      context: ./backend # Dockerfile이 있는 경로
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:5000 # 호스트:컨테이너 포트 매핑
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    depends_on: # db 서비스에 대한 의존성 추가
      - db
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"

#volumes:
#db-data:

networks:
  app-network:
    driver: bridge
