services:
  db:
    container_name: db
    image: postgres:17.3
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=richmindful100@#
      - POSTGRES_DB=bit
    ports:
      - 5432:5432
    logging:
      options:
        max-file: "3"
        max-size: "250m"

  adminer:
    container_name: adminer
    image: dockette/adminer:dg
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db

  crawling:
    container_name: crawling
    build: 
      context: ./crawling  # Dockerfile이 있는 경로
      dockerfile: Dockerfile
    restart: no #always
    #volumes:
      #- ./crawling/app:/app
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"

  vector_rag:
    container_name: vector_rag
    build: 
      context: ./vector_rag  # Dockerfile이 있는 경로
      dockerfile: Dockerfile
    restart: no #always
    ports:
      - 5001:8000
    depends_on:
      - ollama
    environment:
      - LANGSMITH_TRACING=true
      - LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
      - LANGSMITH_API_KEY=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
      - LANGSMITH_PROJECT="vector_store"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "250m"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: